### ISSUE TITLE
build failure:  missing aclocal-1.14

### ISSUE THREAD

**Issue by alexquinn** [neurobin/rnm#13]
`./configure` works, but when I try to `make`, I get `aclocal-1.14: command not found` and `WARNING: 'aclocal-1.14' is missing on your system.`.  If I edit the Makefile and replace "1.14" with "1.11" (the version of autoconf on my system) then it gets further, but then I get `error: possibly undefined macro: AC_CHECK_HEADER_STDBOOL`.

This is probably just a case of trying to run new code on an old system (Red Hat EL 6.8).  The binary also did not work due to glibc/glibcxx version issues.  However, if this requires autoconf ≥1.14, you might consider mentioning that in the documentation.   You since it requires libstdc++6 (>=4.9.2), you might want to mention how to check that.

(To be clear, I'm not looking for help for my own benefit.  I just thought you might want to know.)

**Comment by neurobin** [comment]
I haven't updated it for  quite a while due to a bug with older std::regex implementation on GCC. The regex operation is broken with new GCC version. I may update it within two weeks though. So, when compiling, compile with <gcc-5.0. Better if you use one of the already built [binaries](https://github.com/neurobin/rnm/tree/bin-release)

And about the aclocal, you can fix it by running `./autogen.sh` first, then `./configure` and `make`

In future version I will try to check for that library with the configure script, but if you already have g++ or equivalent compiler installed then you don't need to worry about the library. It's already installed.

I also want to mention that all C++ regex is going to be completely replaced by PCRE2 regex.

**Comment by neurobin** [comment]
Finally I got some time to work on it. It's updated with brand new features :D And I mentioned about the automake version issue in the installation process as you suggested.

And the libstdc++6 is required for runtime. If you are compiling rnm from source you don't need to worry about it. Only pre-built binary has a **fixed** dependency on standard C and C++ library, like libc6 and libstdc++6. The current ubuntu build uses libstdc++6-5.4.0 (later will work but not older), and the x64/x32 binaries in the [release](https://github.com/neurobin/rnm/releases) depends on libstdc++6-4.8.5 and later
