### ISSUE TITLE
Force isn't applied?

### ISSUE THREAD

**Issue by kud** [neurobin/rnm#31]
`rnm -rs "/-CONFLICT-1//gi" -dp 10000 --force ./*`

`rnm -rs "/-CONFLICT-1//gi" -dp 10000 -f ./*`

`rnm -rs "/-CONFLICT-1//gi" -f -dp 10000 ./*

=> `A file or directory with new name exists`

**Comment by neurobin** [comment]
> => A file or directory with new name exists

It can not rename if a file or directory exists with the same name because it's no longer a rename operation but a move operation which is very dangerous.

For example, let's say a file a.txt (10MB) exists and you are renaming b.txt (a 2KB file) to a.txt. This is an operation that is trying to **replace** a completely different file. This is not allowed even in forced or double forced mode.

**Comment by kud** [comment]
Ooooooh, okay, thank you @neurobin !
