### ISSUE TITLE
How to replace spaces with underscores?

### ISSUE THREAD

**Issue by unclebrr** [neurobin/rnm#5]
Hello and thanks for a very useful utility!
I'm a newbie to *nix and my quiestion might be silly:
How can I rename group of files with spaces to the same with underline?
I mean 01 - file with spaces.ext to 01_-_file_with_spaces.ext
It seens to be easy, but reading man rnm didn't help.

**Comment by unclebrr** [comment]
There's more information that I would need to give you an exact and to the point answer.  Anyway, here goes:

If it's only files (not directory) with .ext extension then

``` sh
rnm -fo -rs '/ /_/g' *.ext
```

If it's any files (not directory)

``` sh
rnm -fo -rs '/ /_/g' *
```

If you need to go inside all subdirectories and do the same

``` sh
rnm -fo -dp -1 -rs '/ /_/g' *
```

or only for .ext:

```
rnm -fo -dp -1 -rs '/ /_/g' -ss '\.ext$' *
```

All of the above commands assume you are running the rnm command inside
the directory where your files reside. Otherwise pass full path instead of *.

Jahid.

**Comment by neurobin** [comment]
@unclebrr 
I have edited your comment to include some amendments, if you don't mind. 

In the last command, using `-ssf` i.e fixed search string was an unintended mistake. Extension needs to be matched at the end, so we need a regex which matches `.ext` at the end of filename.

And, when passing directory as an argument and you intend to go inside that directory to rename files, you must pass a depth value with `-dp` option. Otherwise the default depth (0) value won't let **rnm** to go inside the directory. A depth value of 1 will go inside the directory but not it's subdirectories; 2,3...etc.. will have meanings accordingly. A depth value of -1 indicates infinite depth.

An example command to rename files in a directory (and all of its' subdirectories) is:

``` sh
rnm -fo -dp -1 -rs '/ /_/g' -ss '\.ext$' /path/to/directory
```

The above command may thorw some warning message if not all of the files contain space i.e when the new name and old name becomes the same. These are harmless. You can simply ignore them. Or if you don't want to see these warning messages, you need to be a little bit clever with your search string i.e search for files with at least one space in their names.

``` sh
rnm -fo -dp -1 -rs '/ /_/g' -ss '.* .*\.ext$' /path/to/directory
```

Regards,
Jahid

**Comment by unclebrr** [comment]
Thank you, I got it.
